kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Chart.Name }}
  labels:
  {{ include "service.labels.standard" . | indent 4 }}
rules:
  - apiGroups:
      - "*"
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "*"
    resources:
      - configMaps
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Chart.Name }}
  labels:
  {{ include "service.labels.standard" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Chart.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}